[features]
seeds = false
skip-lint = false
[programs.localnet]
wba_auction_house = "2gcFaJwn6AcRqgZdKSmTPjHJAXpwKu3EH67DFHThzpbP"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/cashmunsy/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
